name: 03 - Workflow Runners
on: push
jobs:
    Ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show Os
              run: |
                echo "This job is running on Ubuntu runner"
                echo "Runner os: $RUNNER_OS"
              
